# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Define Departments, Courses, and Lecturers

puts "Reset Seeds ..."

Course.delete_all
Lecturer.delete_all
Department.delete_all
FileType.delete_all

file_type_list =[
  'Exam Solutions',
  'Quiz Solutions',
  'Project Solutions',
  'Homework/Problem Set Solutions',
  'Course Notes',
  'Books and Resources',
  'Study Guide/Cheat Sheets',
  'Class Recordings',
  'Other'
]

department_list = [
  ['MKTG', 'Marketing'],
  ['MGEC', 'Mangerial Economics'], #Crossover with BEPP
  ['STAT', 'Statistics'],
  ['OID',  'Operations, Information and Decisions'],
  ['ACCT', 'Accounting'],
  ['FCNE', 'Finance'],
  ['LGST', 'Legal Studies & Business Ethics'],
  ['REAL', 'Real Estate'],
  ['BEPP', 'Business Economics & Public Policy'],
  ['MGMT', 'Management'],
  ['HCMG', 'Health Care Management']
]

lecturers_list = [
  ['MKTG', 'J. Scott', 'Armstrong'],
  ['MKTG', 'David', 'Bell'],
  ['MKTG', 'Xinmei', 'Zhang'],
  ['MKTG', 'Yongge', 'Dai Professor'],
  ['MKTG', 'Jonah', 'Berger'],
  ['MKTG','Ron', 'Berman'],
  ['MKTG','Eric T', 'Bradlow'],
  ['MKTG','Jehoshua', 'Eliashberg'],
  ['MKTG','Peter', 'Fader'],
  ['MKTG','J. Wesley', 'Hutchinson'],
  ['MKTG','Stephen J.', 'Heyman'],
  ['MKTG','Raghuram', 'Iyengar'],
  ['MKTG','Barbara E.', 'Kahn'],
  ['MKTG','Barbara', 'Mellers'],
  ['MKTG','Shiri', 'Melumad'],
  ['MKTG','Robert', 'Meyer'],
  ['MKTG','Gideon', 'Nave'],
  ['MKTG','Aviv', 'Nevo'],
  ['MKTG','Michael', 'Platt'],
  ['MKTG','Jagmohan', 'Raju'],
  ['MKTG','Americus', 'Reed'],
  ['MKTG','David', 'Reibstein'],
  ['MKTG','Thomas S.', 'Robertson'],
  ['MKTG','Rom Y.', 'Schrift'],
  ['MKTG','Marissa A.', 'Sharif'],
  ['MKTG','Deborah', 'Small'],
  ['MKTG','Christophe', 'Van den Bulte'],
  ['MKTG','Patti', 'Williams'],
  ['MKTG','Pinar', 'Yildirim'],
  ['MKTG','Z. John', 'Zhang'],
  ['MKTG','Gérard', 'Cachon'],
  ['MKTG','Ulrich', 'Doraszelski'],
  ['MKTG','Emily', 'Falk'],
  ['MKTG','Kartik', 'Hosanagar'],
  ['MKTG','Joseph', 'Kable'],
  ['MKTG','Abba M.', 'Krieger'],
  ['MKTG','Joseph', 'Simmons'],
  ['MKTG','Uri', 'Simonsohn'],
  ['MKTG','John', 'Clithero'],
  ['MKTG','Elea McDonnell', 'Feit'],
  ['MKTG','Daniel Gray', 'Goldstein'],
  ['MKTG','Bari', 'Harlam'],
  ['MKTG','Martin R.', 'Lautman'],
  ['MKTG','Keith', 'Niedermeier'],
  ['MKTG','Jason', 'Riis'],
  ['MKTG','Nancy F.', 'Sheridan'],
  ['MKTG','Kathryn Sharpe', 'Wessling'],
  ["STAT","Bhaswar B.","Bhattacharya"],
  ["STAT","Lawrence D.","Brown"],
  ["STAT","Andreas","Buja"],
  ["STAT","Tony","Cai"],
  ["STAT","Jian","Ding"],
  ["STAT","Edgar","Dobriban"],
  ["STAT","Edward I.","George"],
  ["STAT","Shane T.","Jensen"],
  ["STAT","Abba M.","Krieger"],
  ["STAT","Jean","Lemaire"],
  ["STAT","Mark G.","Low"],
  ["STAT","Zongming","Ma"],
  ["STAT","Alexander","Rakhlin"],
  ["STAT","Paul R.","Rosenbaum"],
  ["STAT","Dylan","Small"],
  ["STAT","J. Michael","Steele"],
  ["STAT","Robert A.","Stine"],
  ["STAT","Weijie","Su"],
  ["STAT","Abraham J.","Wyner"],
  ["STAT","Nancy","Zhang"],
  ["STAT","Linda","Zhao"],
  ["STAT","Richard A.","Berk"],
  ["STAT","Robert F.","Boruch"],
  ["STAT","Eric T","Bradlow"],
  ["STAT","Francis X.","Diebold"],
  ["STAT","Michael","Kearns"],
  ["STAT","Richard","Landis"],
  ["STAT","Hongzhe","Li"],
  ["STAT","Mingyao","Li"],
  ["STAT","Robin","Pemantle"],
  ["STAT","Gregory","Ridgeway"],
  ["STAT","Emil","Pitkin"],
  ["STAT","Richard Paul","Waterman"],
  ["STAT","Yuancheng","Zhu"],
  ["STAT","Warren","Ewens"],
  ["STAT","Dean P.","Foster"],
  ["STAT","Ezra","Krendel"],
  ["STAT","Edward J","Lusk"],
  ["STAT","Donald","Morrison"],
  ["STAT","James","Pickands"],
  ["STAT","Paul","Shaman"],
  ["BEPP","Jose Miguel","Abito"],
  ["BEPP","Santosh","Anagol"],
  ["BEPP","Eduardo","Azevedo"],
  ["BEPP","Ulrich","Doraszelski"],
  ["BEPP","Clayton","Featherstone"],
  ["BEPP","Joseph","Harrington"],
  ["BEPP","Robert","Jensen"],
  ["BEPP","Judd B.","Kessler"],
  ["BEPP","Benjamin B.","Lockwood"],
  ["BEPP","Corinne","Low"],
  ["BEPP","Olivia S.","Mitchell"],
  ["BEPP","Katja","Seim"],
  ["BEPP","Kent","Smetters"],
  ["BEPP","Arthur","van Benthem"],
  ["BEPP","Shing-Yi","Wang"],
  ["BEPP","David S.","Abrams"],
  ["BEPP","Tom","Baker"],
  ["BEPP","Iwan","Barankay"],
  ["BEPP","Fernando","Ferreira"],
  ["BEPP","Joseph","Gyourko"],
  ["BEPP","Scott E.","Harrington"],
  ["BEPP","Ann","Harrison"],
  ["BEPP","Robert P.","Inman"],
  ["BEPP","Howard","Kunreuther"],
  ["BEPP","Jean","Lemaire"],
  ["BEPP","Marc","Meredith"],
  ["BEPP","Mark V.","Pauly"],
  ["BEPP","Chris","Sanchirico"],
  ["BEPP","Todd","Sinai"],
  ["BEPP","David A.","Cather"],
  ["BEPP","Stephen","Golub"],
  ["BEPP","G. Victor","Hallman"],
  ["BEPP","Ayse","Kaya"],
  ["BEPP","Ellen","Magenheim"],
  ["BEPP","Gregory","Nini"],
  ["BEPP","Gizem","Saka"],
  ["BEPP","Heather","Schofield"],
  ["BEPP","W. Bruce","Allen"],
  ["BEPP","David F","Babbel"],
  ["BEPP","Elizabeth E.","Bailey"],
  ["BEPP","John David","Cummins"],
  ["BEPP","Neil A","Doherty"],
  ["BEPP","Gerald R.","Faulhaber"],
  ["BEPP","Dan M.","McGill"],
  ["BEPP","Howard","Pack"],
  ["BEPP","Janet Rothenberg","Pack"],
  ["BEPP","Jerry S","Rosenbloom"],
  ["BEPP","Arie P.","Schinnar"],
  ["BEPP","Anita A.","Summers"],
  ["MGEC","Jose Miguel","Abito"],
  ["MGEC","Santosh","Anagol"],
  ["MGEC","Eduardo","Azevedo"],
  ["MGEC","Ulrich","Doraszelski"],
  ["MGEC","Clayton","Featherstone"],
  ["MGEC","Joseph","Harrington"],
  ["MGEC","Robert","Jensen"],
  ["MGEC","Judd B.","Kessler"],
  ["MGEC","Benjamin B.","Lockwood"],
  ["MGEC","Corinne","Low"],
  ["MGEC","Olivia S.","Mitchell"],
  ["MGEC","Katja","Seim"],
  ["MGEC","Kent","Smetters"],
  ["MGEC","Arthur","van Benthem"],
  ["MGEC","Shing-Yi","Wang"],
  ["MGEC","David S.","Abrams"],
  ["MGEC","Tom","Baker"],
  ["MGEC","Iwan","Barankay"],
  ["MGEC","Fernando","Ferreira"],
  ["MGEC","Joseph","Gyourko"],
  ["MGEC","Scott E.","Harrington"],
  ["MGEC","Ann","Harrison"],
  ["MGEC","Robert P.","Inman"],
  ["MGEC","Howard","Kunreuther"],
  ["MGEC","Jean","Lemaire"],
  ["MGEC","Marc","Meredith"],
  ["MGEC","Mark V.","Pauly"],
  ["MGEC","Chris","Sanchirico"],
  ["MGEC","Todd","Sinai"],
  ["MGEC","David A.","Cather"],
  ["MGEC","Stephen","Golub"],
  ["MGEC","G. Victor","Hallman"],
  ["MGEC","Ayse","Kaya"],
  ["MGEC","Ellen","Magenheim"],
  ["MGEC","Gregory","Nini"],
  ["MGEC","Gizem","Saka"],
  ["MGEC","Heather","Schofield"],
  ["MGEC","W. Bruce","Allen"],
  ["MGEC","David F","Babbel"],
  ["MGEC","Elizabeth E.","Bailey"],
  ["MGEC","John David","Cummins"],
  ["MGEC","Neil A","Doherty"],
  ["MGEC","Gerald R.","Faulhaber"],
  ["MGEC","Dan M.","McGill"],
  ["MGEC","Howard","Pack"],
  ["MGEC","Janet Rothenberg","Pack"],
  ["MGEC","Jerry S","Rosenbloom"],
  ["MGEC","Arie P.","Schinnar"],
  ["MGEC","Anita A.","Summers"],
  ["ACCT","Christopher","Armstrong"],
  ["ACCT","Matthew","Bloomfield"],
  ["ACCT","Jennifer","Blouin"],
  ["ACCT","Brian","Bushee"],
  ["ACCT","Matthew","Cedergren"],
  ["ACCT","Carolyn","Deller"],
  ["ACCT","Paul","Fischer"],
  ["ACCT","Nicholas J.","Gonedes"],
  ["ACCT","Wayne","Guay"],
  ["ACCT","Luzi","Hail"],
  ["ACCT","Mirko S.","Heinle"],
  ["ACCT","Robert W.","Holthausen"],
  ["ACCT","Christopher D.","Ittner"],
  ["ACCT","Richard A.","Lambert"],
  ["ACCT","Jeremy","Michels"],
  ["ACCT","Allison","Nicoletti"],
  ["ACCT","Catherine M.","Schrand"],
  ["ACCT","Stephanie","Sikes"],
  ["ACCT","Daniel","Taylor"],
  ["ACCT","Robert E.","Verrecchia"],
  ["ACCT","Frank","Zhou"],
  ["ACCT","Salman","Arif"],
  ["ACCT","Victor","Defeo"],
  ["ACCT","Karl","Fassnacht"],
  ["ACCT","Peggy Bishop","Lane"],
  ["FNCE","Andrew B.","Abel"],
  ["FNCE","Jules","van Binsbergen"],
  ["FNCE","Domenico","Cuoco"],
  ["FNCE","William","Diamond"],
  ["FNCE","Winston Wei","Dou"],
  ["FNCE","Michael R.","Gibbons"],
  ["FNCE","Erik","Gilje"],
  ["FNCE","Vincent","Glode"],
  ["FNCE","Itay","Goldstein"],
  ["FNCE","Joao F.","Gomes"],
  ["FNCE","Bulent","Gultekin"],
  ["FNCE","Richard J.","Herring"],
  ["FNCE","Robert P.","Inman"],
  ["FNCE","Jeffrey F.","Jaffe"],
  ["FNCE","Urban","Jermann"],
  ["FNCE","Donald B.","Keim"],
  ["FNCE","Richard E.","Kihlstrom"],
  ["FNCE","Tim","Landvoigt"],
  ["FNCE","Doron","Levit"],
  ["FNCE","Karen K.","Lewis"],
  ["FNCE","A. Craig","MacKinlay"],
  ["FNCE","Richard","Marston"],
  ["FNCE","Pricila","Maziero"],
  ["FNCE","David","Musto"],
  ["FNCE","Christian","Opp"],
  ["FNCE","Krishna","Ramaswamy"],
  ["FNCE","Michael","Roberts"],
  ["FNCE","Nikolai","Roussanov"],
  ["FNCE","Krista","Schwarz"],
  ["FNCE","Jeremy","Siegel"],
  ["FNCE","Nicholas S.","Souleles"],
  ["FNCE","Robert F.","Stambaugh"],
  ["FNCE","Luke","Taylor"],
  ["FNCE","Jessica","Wachter"],
  ["FNCE","Chaojun","Wang"],
  ["FNCE","Amir","Yaron"],
  ["FNCE","Bilge","Yilmaz"],
  ["FNCE","John Yiran","Zhu"],
  ["FNCE","Francis X.","Diebold"],
  ["FNCE","Joseph","Gyourko"],
  ["FNCE","Robert W.","Holthausen"],
  ["FNCE","Andrew","Postlewaite"],
  ["FNCE","Susan M.","Wachter"],
  ["FNCE","Martin A.","Asher"],
  ["FNCE","Ravi","Bansal"],
  ["FNCE","David","Bard"],
  ["FNCE","Gordon","Bodnar"],
  ["FNCE","Stephan","Dieckmann"],
  ["FNCE","Zvi","Eckstein"],
  ["FNCE","Ronel","Elul"],
  ["FNCE","David","Erickson"],
  ["FNCE","Burcu","Esmer"],
  ["FNCE","Vito D.","Gala"],
  ["FNCE","Christopher","Geczy"],
  ["FNCE","Gabriel","Hawawini"],
  ["FNCE","Kevin","Kaiser"],
  ["FNCE","Howard","Kaufold"],
  ["FNCE","Shimon","Kogan"],
  ["FNCE","Anthony","Landry"],
  ["FNCE","Loretta J.","Mester"],
  ["FNCE","Stephen","Meyer"],
  ["FNCE","Tayyeb","Shabbir"],
  ["FNCE","Karin","Thorburn"],
  ["FNCE","David","Wessels"],
  ["HCMG","Abby E.","Alpert"],
  ["HCMG","Lawton R.","Burns"],
  ["HCMG","Guy","David"],
  ["HCMG","Ezekiel J.","Emanuel"],
  ["HCMG","Matthew","Grennan"],
  ["HCMG","Atul","Gupta"],
  ["HCMG","Scott E.","Harrington"],
  ["HCMG","Mark V.","Pauly"],
  ["HCMG","Ashley","Swanson"],
  ["HCMG","David A.","Asch"],
  ["HCMG","Tom","Baker"],
  ["HCMG","Henry","Glick"],
  ["HCMG","John R.","Kimberly"],
  ["HCMG","Mitesh","Patel"],
  ["HCMG","Daniel","Polsky"],
  ["HCMG","J. Sanford","Schwartz"],
  ["HCMG","Jeffrey H.","Silber"],
  ["HCMG","Kevin","Volpp"],
  ["HCMG","Rachel","Werner"],
  ["HCMG","Sankey V.","Williams"],
  ["HCMG","Molly","Candon"],
  ["HCMG","John","Glaser"],
  ["HCMG","Eric","Heil"],
  ["HCMG","June M.","Kinney"],
  ["HCMG","Gary","Kurtzman"],
  ["HCMG","Jeffrey","Libson"],
  ["HCMG","Hari","Mahadevan"],
  ["HCMG","Steven","Nichtberger"],
  ["HCMG","Doug","Present"],
  ["HCMG","Stephen","Sammut"],
  ["HCMG","Jeffrey","Solomon"],
  ["HCMG","John","Whitman"],
  ["HCMG","Ravi","Bansal"],
  ["HCMG","David","Bard"],
  ["HCMG","Gordon","Bodnar"],
  ["HCMG","Stephan","Dieckmann"],
  ["HCMG","Zvi","Eckstein"],
  ["HCMG","Ronel","Elul"],
  ["HCMG","David","Erickson"],
  ["HCMG","Burcu","Esmer"],
  ["HCMG","Vito D.","Gala"],
  ["HCMG","Christopher","Geczy"],
  ["HCMG","Gabriel","Hawawini"],
  ["HCMG","Kevin","Kaiser"],
  ["HCMG","Howard","Kaufold"],
  ["HCMG","Shimon","Kogan"],
  ["HCMG","Anthony","Landry"],
  ["HCMG","Loretta J.","Mester"],
  ["HCMG","Stephen","Meyer"],
  ["HCMG","Tayyeb","Shabbir"],
  ["HCMG","Karin","Thorburn"],
  ["HCMG","David","Wessels"],
  ["LGST","Janice","Bellace"],
  ["LGST","Brian","Berkey"],
  ["LGST","Vincent","Buccola"],
  ["LGST","Peter","Conti-Brown"],
  ["LGST","Thomas","Donaldson"],
  ["LGST","Gwendolyn","Gordon"],
  ["LGST","Herbert","Hovenkamp"],
  ["LGST","Robert","Hughes"],
  ["LGST","Julian","Jonker"],
  ["LGST","William S.","Laufer"],
  ["LGST","Sarah E.","Light"],
  ["LGST","Philip M.","Nichols"],
  ["LGST","Eric W.","Orts"],
  ["LGST","Diana C.","Robertson"],
  ["LGST","Amy","Sepinwall"],
  ["LGST","G. Richard","Shell"],
  ["LGST","Nina","Strohminger"],
  ["LGST","Alan","Strudler"],
  ["LGST","Kevin","Werbach"],
  ["LGST","David","Zaring"],
  ["LGST","Mitchell N.","Berman"],
  ["LGST","Cristina","Bicchieri"],
  ["LGST","Jill","Fisch"],
  ["LGST","Beth A.","Simmons"],
  ["LGST","José","Anderson"],
  ["LGST","Mason","Ashe"],
  ["LGST","Jennifer","Beer"],
  ["LGST","Edward J.","Bergman"],
  ["LGST","Nazli M","Bhatia"],
  ["LGST","Steven","Blum"],
  ["LGST","Robert J","Borghese"],
  ["LGST","Melinda","deLisle"],
  ["LGST","Stuart","Diamond"],
  ["LGST","Charles","Forer"],
  ["LGST","Pierre","Gentin"],
  ["LGST","E. Carolyn","Hochstadter-Dicker"],
  ["LGST","Brian","Hutler"],
  ["LGST","Roger","Machlis"],
  ["LGST","Jerrilyn","Marston"],
  ["LGST","Eric","Max"],
  ["LGST","Arthur","McAfee"],
  ["LGST","Djordjija","Petkoski"],
  ["LGST","Milan","Prilepok"],
  ["LGST","Nicholas","Rongione"],
  ["LGST","Scott","Rosner"],
  ["LGST","Ronald","Sarachan"],
  ["LGST","Mark","Schwartz"],
  ["LGST","Mori","Taheripour"],
  ["LGST","Deborah","Weinstein"],
  ["MGMT","Raffi","Amit"],
  ["MGMT","Rachel","Arnett"],
  ["MGMT","Valentina","Assenova"],
  ["MGMT","Iwan","Barankay"],
  ["MGMT","Sigal","Barsade"],
  ["MGMT","Matthew","Bidwell"],
  ["MGMT","Peter","Cappelli"],
  ["MGMT","Andrew","Carton"],
  ["MGMT","Adam","Cobb"],
  ["MGMT","Stephanie","Creary"],
  ["MGMT","Emilie","Feldman"],
  ["MGMT","Geoffrey","Garrett"],
  ["MGMT","Claudine","Gartenberg"],
  ["MGMT","Aline","Gatignon"],
  ["MGMT","Adam","Grant"],
  ["MGMT","Mauro","Guillen"],
  ["MGMT","Martine","Haas"],
  ["MGMT","Ann","Harrison"],
  ["MGMT","Witold","Henisz"],
  ["MGMT","Exequiel","Hernandez"],
  ["MGMT","David","Hsu"],
  ["MGMT","Laura","Huang"],
  ["MGMT","Rahul","Kapoor"],
  ["MGMT","John R.","Kimberly"],
  ["MGMT","Jacqueline","Kirtley"],
  ["MGMT","Katherine","Klein"],
  ["MGMT","Daniel A.","Levinthal"],
  ["MGMT","John Paul","MacDuffie"],
  ["MGMT","Ian","MacMillan"],
  ["MGMT","Mary-Hunter","McDonnell"],
  ["MGMT","Anoop","Menon"],
  ["MGMT","Ethan","Mollick"],
  ["MGMT","Samir","Nurmohamed"],
  ["MGMT","Daniel","Raff"],
  ["MGMT","Luis A.","Rios"],
  ["MGMT","Lori","Rosenkopf"],
  ["MGMT","Nancy","Rothbard"],
  ["MGMT","Arkadiy","Sakhartov"],
  ["MGMT","Nicolaj","Siggelkow"],
  ["MGMT","Harbir","Singh"],
  ["MGMT","Philip","Tetlock"],
  ["MGMT","Louis A.","Thomas"],
  ["MGMT","Michael","Useem"],
  ["MGMT","Natalya","Vinokurova"],
  ["MGMT","Keith W.","Weigelt"],
  ["MGMT","Tyler","Wry"],
  ["MGMT","Minyuan","Zhao"],
  ["MGMT","Janice","Bellace"],
  ["MGMT","Joseph R.","Biden"],
  ["MGMT","Lawton R.","Burns"],
  ["MGMT","Eric K.","Clemons"],
  ["MGMT","Jerry","Jacobs"],
  ["MGMT","Eric W.","Orts"],
  ["MGMT","Maurice","Schweitzer"],
  ["MGMT","G. Richard","Shell"],
  ["MGMT","Karl","Ulrich"],
  ["MGMT","Saikat","Chaudhuri"],
  ["MGMT","Doug","Collom"],
  ["MGMT","Stewart","Friedman"],
  ["MGMT","Anne","Greenhalgh"],
  ["MGMT","Martin","Ihrig"],
  ["MGMT","Sonia","Marciano"],
  ["MGMT","Sara Jane","McCaffrey"],
  ["MGMT","Payal","Sharma"],
  ["MGMT","Gregory P","Shea"],
  ["MGMT","Bobbi","Thomason"],
  ["MGMT","Adrian E.","Tschoegl"],
  ["OID","Gad","Allon"],
  ["OID","Gérard","Cachon"],
  ["OID","Eric K.","Clemons"],
  ["OID","Morris A.","Cohen"],
  ["OID","Marshall L.","Fisher"],
  ["OID","Noah","Gans"],
  ["OID","Etan","Green"],
  ["OID","Monique","Guignard-Spielberg"],
  ["OID","Lorin M.","Hitt"],
  ["OID","Kartik","Hosanagar"],
  ["OID","Steven O.","Kimbrough"],
  ["OID","Howard","Kunreuther"],
  ["OID","Simone","Marinesi"],
  ["OID","Katherine L.","Milkman"],
  ["OID","Ken","Moon"],
  ["OID","Alice","Moon"],
  ["OID","Serguei","Netessine"],
  ["OID","Alex","Rees-Jones"],
  ["OID","Sergei","Savin"],
  ["OID","Rebecca","Schaumberg"],
  ["OID","Maurice","Schweitzer"],
  ["OID","Joseph","Simmons"],
  ["OID","Uri","Simonsohn"],
  ["OID","Hummy","Song"],
  ["OID","Xuanming","Su"],
  ["OID","Prasanna","Tambe"],
  ["OID","Christian","Terwiesch"],
  ["OID","Gerry","Tsoukalas"],
  ["OID","Karl","Ulrich"],
  ["OID","Senthil","Veeraraghavan"],
  ["OID","Lynn","Wu"],
  ["OID","David A.","Asch"],
  ["OID","Jonathan","Baron"],
  ["OID","Angela","Duckworth"],
  ["OID","Jehoshua","Eliashberg"],
  ["OID","Michael","Kearns"],
  ["OID","Abba M.","Krieger"],
  ["OID","Heather","Schofield"],
  ["OID","J. Michael","Steele"],
  ["OID","Lyle","Ungar"],
  ["OID","Rachel","Werner"],
  ["OID","Omar","Besbes"],
  ["OID","Clay","Burns"],
  ["OID","Taylor","Caputo"],
  ["OID","Ziv","Katalan"],
  ["OID","Edwin","Keh"],
  ["OID","Shirit","Kronzon"],
  ["OID","Alex","Markle"],
  ["OID","Cade","Massey"],
  ["OID","Maria","Rieders"],
  ["OID","David","Robertson"],
  ["OID","Jeremy A.","Yip"],
  ["OID","Saikat","Chaudhuri"],
  ["OID","Doug","Collom"],
  ["OID","Stewart","Friedman"],
  ["OID","Anne","Greenhalgh"],
  ["OID","Martin","Ihrig"],
  ["OID","Sonia","Marciano"],
  ["OID","Sara Jane","McCaffrey"],
  ["OID","Payal","Sharma"],
  ["OID","Gregory P","Shea"],
  ["OID","Bobbi","Thomason"],
  ["OID","Adrian E.","Tschoegl"],
  ["REAL","Gilles","Duranton"],
  ["REAL","Fernando","Ferreira"],
  ["REAL","Joseph","Gyourko"],
  ["REAL","Jessie","Handbury"],
  ["REAL","Mariaflavia","Harari"],
  ["REAL","Benjamin","Keys"],
  ["REAL","Todd","Sinai"],
  ["REAL","Susan M.","Wachter"],
  ["REAL","Maisy","Wong"],
  ["REAL","Robert P.","Inman"],
  ["REAL","Michael","Knoll"],
  ["REAL","Sam","Chandan"],
  ["REAL","Alan","Feldman"],
  ["REAL","Marja C.","Hoek-Smit"],
  ["REAL","Robert","Lane"],
  ["REAL","William","Martin"],
  ["REAL","Asuka","Nakahara"],
  ["REAL","Joseph","Simmons"],
  ["REAL","Uri","Simonsohn"],
  ["REAL","Hummy","Song"],
  ["REAL","Xuanming","Su"],
  ["REAL","Prasanna","Tambe"],
  ["REAL","Christian","Terwiesch"],
  ["REAL","Gerry","Tsoukalas"],
  ["REAL","Karl","Ulrich"],
  ["REAL","Senthil","Veeraraghavan"],
  ["REAL","Lynn","Wu"],
  ["REAL","David A.","Asch"],
  ["REAL","Jonathan","Baron"],
  ["REAL","Angela","Duckworth"],
  ["REAL","Jehoshua","Eliashberg"],
  ["REAL","Michael","Kearns"],
  ["REAL","Abba M.","Krieger"],
  ["REAL","Heather","Schofield"],
  ["REAL","J. Micheal","Steele"],
  ["REAL","Lyle","Ungar"],
  ["REAL","Rachel","Werner"],
  ["REAL","Omar","Besbes"],
  ["REAL","Clay","Burns"],
  ["REAL","Taylor","Caputo"],
  ["REAL","Ziv","Katalan"],
  ["REAL","Edwin","Keh"],
  ["REAL","Shirit","Kronzon"],
  ["REAL","Alex","Markle"],
  ["REAL","Cade","Massey"],
  ["REAL","Maria","Rieders"],
  ["REAL","David","Robertson"],
  ["REAL","Jeremy A.","Yip"],
  ["REAL","Saikat","Chaudhuri"],
  ["REAL","Doug","Collom"],
  ["REAL","Stewart","Friedman"],
  ["REAL","Anne","Greenhalgh"],
  ["REAL","Martin","Ihrig"],
  ["REAL","Sonia","Marciano"],
  ["REAL","Sara Jane","McCaffrey"],
  ["REAL","Payal","Sharma"],
  ["REAL","Gregory P","Shea"],
  ["REAL","Bobbi","Thomason"],
  ["REAL","Adrian W.","Tschoegl"]
]

courses_list =[
  ['MKTG', '611', 'MARKETING MANAGEMENT'],
  ['MKTG', '612', 'DYNAMIC MKTG STRATEGY'],
  ['MKTG', '613', 'STRATGIC MKTG SIMULATION'],
  ['MKTG', '711', 'CONSUMER BEHAVIOR'],
  ['MKTG', '712', 'DATA & ANLZ FOR MKTG DEC'],
  ['MKTG', '724', 'ADVERTISING MANAGEMENT'],
  ['MKTG', '725', 'PRINCIPLES OF RETAILING'],
  ['MKTG', '727', 'MKTG AND ELECTRONIC COMM'],
  ['MKTG', '734', 'CREATIVITY'],
  ['MKTG', '741', 'ENTREPRENEURIAL MKTG'],
  ['MKTG', '754', 'PRICING POLICY'],
  ['MKTG', '770', 'DGTL SOCIAL & E-COM MKTG'],
  ['MKTG', '771', 'MODELS FOR MKTG STRATEGY'],
  ['MKTG', '775', 'MANAGING CUSTOMER VALUE'],
  ['MKTG', '776', 'APPL PROB MODELS MKTG'],
  ['MKTG', '777', 'MARKETING STR'],
  ['MKTG', '778', 'STRATEGIC BRAND MGMT'],
  ['MKTG', '806', 'SPECIAL TOPICS'],
  ["ACCT","611","FINANCIAL ACCOUNTING"],
  ["ACCT","612","ACCELERATED FIN ACCT"],
  ["ACCT","613","FIN AND MNGL ACCT"],
  ["ACCT","706","COST MANAGEMENT"],
  ["ACCT","718","AUDITING"],
  ["ACCT","742","PROBLEMS IN FIN REPORTIN"],
  ["ACCT","743","ACCT FOR COMPLX FIN STRC"],
  ["ACCT","747","FIN STATEMENT & DIS ANA "],
  ["ACCT","897","TAXES AND BUS STRATEGY"],
  ["LGST","611","RESP IN GLOBAL MGMT"],
  ["LGST","612","RESPONSIBILITY IN BUS."],
  ["LGST","641","BUSINESS ENTERPRISE"],
  ["LGST","642","BIG DATA, BIG RESP"],
  ["LGST","643","OTHER PEOPLE'S MONEY"],
  ["LGST","802","GLOBAL CORP LAW & MGMT"],
  ["LGST","804","REAL ESTATE LAW"],
  ["LGST","805","LAW OF MKTG & ANTITRUST"],
  ["LGST","806","NEGOTIATIONS"],
  ["LGST","807","SECURITIES REG"],
  ["LGST","809","SPORTS BUSINESS MGMT"],
  ["LGST","813","LEG ASP ENTREPRENRSHP"],
  ["LGST","815","ENVTL MGMT LAW & POL"],
  ["LGST","820","INTL BUSINESS ETHICS "],
  ["REAL","708","HOUSING MARKETS"],
  ["REAL","721","REAL ESTATE INVESTMENTS"],
  ["REAL","723","INTRO TO REAL ESTATE"],
  ["REAL","724","URBAN REAL ESTATE ECON"],
  ["REAL","730","URBAN FISCAL POLICY"],
  ["REAL","772","URB PUB POL & PRIV DEVEL"],
  ["REAL","804","REAL ESTATE LAW"],
  ["REAL","821","REAL ESTATE DEVELOPMENT "],
  ["REAL","836","INTL HOUSING COMPARISNS"],
  ["REAL","840","ADV REAL EST INV, ANALYS "],
  ["REAL","890","INTL REAL EST COMPARISN "],
  ["REAL","891","REAL ESTATE ENTREPRENEUR"],
  ["BEPP","704","FINANCING GOVERNMENT"],
  ["BEPP","708","HOUSING MARKETS"],
  ["BEPP","710","FIRMS, MARKETS & PUBLIC"],
  ["BEPP","761","RISK ANALY & ENV MGMT"],
  ["BEPP","763","ENERGY MARKETS & POLICY "],
  ["BEPP","770","INTRO TO BUSINESS ECONOM"],
  ["BEPP","772","URB PUB POL & PRIV DEVEL"],
  ["BEPP","773","URBAN FISCAL POLICY"],
  ["BEPP","780","APPLIED DATA ANALYSIS"],
  ["BEPP","789","NATIONS, POL AND MARKETS"],
  ["BEPP","805","RISK MANAGEMENT"],
  ["BEPP","811","RISK AND CRISIS MGMT"],
  ["BEPP","812","MARKETS FOR PURE RISK"],
  ["BEPP","823","BUS INSR & EST PLNG"],
  ["BEPP","836","INTL HOUSING COMPARISNS "],
  ["BEPP","851","FUND OF ACT SCI I"],
  ["BEPP","852","FUND OF ACTUARIAL SCI II "],
  ["BEPP","853","ACTUARIAL STATISTICS"],
  ["BEPP","854","APPL STAT METHD FOR ACTU"],
  ["BEPP","895","GLOBAL BUSINESS WEEK"],
  ["MGEC","611","MICROECONOMICS FOR MANAG "],
  ["MGEC","612","MICROECON FOR MGR - ADV"],
  ["MGMT","610","FOUND OF TEAMWRK & LDRSH"],
  ["MGMT","611","MANAGING EST ENTERPRISE"],
  ["MGMT","612","MANAGING EMERG ENTRPRSE"],
  ["MGMT","613","MANAG ESTAB ENTERPRISE"],
  ["MGMT","624","LEADING DIVERSITY IN ORG"],
  ["MGMT","625","CORP. GOVERNANCE EXEC"],
  ["MGMT","671","EXECUTIVE LEADERSHIP"],
  ["MGMT","690","MANAGERIAL DECISN MAKING"],
  ["MGMT","691","NEGOTIATIONS"],
  ["MGMT","701","STRAT & COMPET ADVANTAGE"],
  ["MGMT","711","COMP STR/IND STR"],
  ["MGMT","712","MNG STRAT PARTNERSHIPS"],
  ["MGMT","714","VALUE CREATION & VAL CAP"],
  ["MGMT","715","POL & SOC ENVIRON OF MM"],
  ["MGMT","720","CORPORATE DIPLOMACY "],
  ["MGMT","721","CORP DEV: MERG & ACQUIS"],
  ["MGMT","729","INTEL PROPERTY STRATEGY"],
  ["MGMT","731","TECHNOLOGY STRATEGY"],
  ["MGMT","740","LEADING EFFECTIVE TEAMS"],
  ["MGMT","751","STRAT MGMT OF HUM ASSETS"],
  ["MGMT","765","VENTURE CAPITAL& ENT MG"],
  ["MGMT","766","FAMILY ENTERPRISE MGMT."],
  ["MGMT","772","POWER & POL IN ORGANIZ"],
  ["MGMT","773","MANAGING ORG CHANGE"],
  ["MGMT","776","CULTIV JUDGMENT SKILLS"],
  ["MGMT","782","STRATEGIC IMPLEMENTATION"],
  ["MGMT","794","UNDERSTANDING CAREERS"],
  ["MGMT","801","ENTREPRENEURSHIP"],
  ["MGMT","802","INNOV, CHG AND ENT"],
  ["MGMT","804","VENTURE CAP & ENT MGMT"],
  ["MGMT","806","VENTURE IMPLEMENTATION"],
  ["MGMT","809","PRIV. EQUITY EMERG. MAR"],
  ["MGMT","810","SOCIAL ENTREPRENEURSHIP"],
  ["MGMT","811","ENTREP THROUGH ACQUIS"],
  ["MGMT","815","SPORTS BUSINESS MGMT"],
  ["MGMT","816","BLDG. HUM ASSETS"],
  ["MGMT","833","STRAT & PRAC OF FAMILY"],
  ["STAT","613","REGR ANALYSIS FOR BUS"],
  ["STAT","621","ACC REGRESSION ANALYSIS"],
  ["STAT","701","MODERN DATA MINING"],
  ["STAT","705","STAT COMPUTING WITH R"],
  ["STAT","711","FORECASTING METHODS MGMT"],
  ["STAT","712","DECISION MAKING"],
  ["STAT","722","PREDICTIVE ANALYTICS"],
  ["STAT","724","TEXT ANALYTICS"],
  ["STAT","770","DATA ANALY & STAT COMP"],
  ["STAT","776","APPL PROB MODELS MKTG"],
  ["STAT","851","FUND OF ACTUARIAL SCI I "],
  ["STAT","852","FUND OF ACTUARIAL SCI II"],
  ["STAT","853","ACTUARIAL STATISTICS"],
  ["STAT","854","APPL STAT METHD FOR ACTU"],
  ["FCNE","611","CORPORATE FINANCE"],
  ["FCNE","612","ACCELERATED CORP FINANCE"],
  ["FCNE","613","MACROECN & GLOBAL ECONOM"],
  ["FCNE","614","CORPORATE FNCE"],
  ["FCNE","615","MACROECONOMICS"],
  ["FCNE","717","FINANCIAL DERIVATIVES"],
  ["FCNE","719","INTL FINANCIAL MARKETS"],
  ["FCNE","720","INVESTMENT MANAGEMENT"],
  ["FCNE","725","FIXED INCOME SECURITIES"],
  ["FCNE","726","ADVANCED CORP FINANCE"],
  ["FCNE","728","CORPORATE VALUATION"],
  ["FCNE","730","URBAN FISCAL POLICY"],
  ["FCNE","731","INTERNATL CORP FINANCE"],
  ["FCNE","732","INTERNATIONAL BANKING"],
  ["FCNE","738","CAPITAL MARKETS"],
  ["FCNE","739","BEHAVIORAL FINANCE"],
  ["FCNE","750","VENT CAP & FNCE INNOVAT"],
  ["FCNE","751","FNCE OF BUYOUTS & ACQS"],
  ["FCNE","754","IMPACT INVESTING"],
  ["FCNE","756","ENERGY FINANCE"],
  ["FCNE","785","BUS STRAT & CORP LAW"],
  ["FCNE","883","STRATEGIC EQUITY FINANCE"],
  ["FCNE","884","ADVANCED TOPICS IN PE"],
  ["FCNE","885","ASP - FIN TECH"],
  ["FCNE","886","ASP - HEDGE FUNDS"],
  ["FCNE","887","ASP-SHAREHOLDER ACTIVISM"],
  ["FCNE","891","ASP-CORP RESTRUCTURING"],
  ["FCNE","893","ASP GLOBAL MONETARY FNCE"],
  ["FCNE","895","ASP PRIVATE EQUITY"],
  ["FCNE","896","FINANCE IN EUROPE"],
  ["FCNE","897","FNCE IN MID EAST & N AFR"],
  ["HCMG","841","HEALTH SERVICES SYS"],
  ["HCMG","845","MANAGED CARE & INTEG HC"],
  ["HCMG","849","FIN MGMT HEALTH INST"],
  ["HCMG","852","HEALTH CARE SERVICES DEL"],
  ["HCMG","853","MEDICAL DEVICES"],
  ["HCMG","855","MGMT HLTH CRE FOR ELDRLY"],
  ["HCMG","859","COMPARATIVE HC SYSTEMS"],
  ["HCMG","863","MGMT&ECONOFPHARM&MEDTECH"],
  ["HCMG","866","E-HEALTH:BUSINESS MODELS"],
  ["HCMG","867","HC ENTREPRENEURSHIP"],
  ["HCMG","868","PRIV SEC ROLE GLOB HLTH"],
  ["HCMG","890","ADVANCED STUDY PROJECT"],
  ["OID","611","QUALITY AND PRODUCTIVITY"],
  ["OID","612","BUSINESS ANALYTICS"],
  ["OID","613","INFO & BUS TRANSFRM"],
  ["OID","614","INNOVATION"],
  ["OID","615","OPERATIONS STRATEGY"],
  ["OID","621","DECISION MDLS&UNCERTNTY"],
  ["OID","632","OP MGMT: SPPLY CHAIN MGT"],
  ["OID","636","SCALING OPERATIONS"],
  ["OID","640","DIGITAL GAME DESIGN TECH"],
  ["OID","642","ANALYTICS FOR SERVICES"],
  ["OID","643","ANALY FOR REVENUE MGMT"],
  ["OID","652","DES&DEV WEB-BASED PROD"],
  ["OID","653","MATH MDLNG APPL IN FNCE"],
  ["OID","654","PRODUCT DESIGN&DEVEL"],
  ["OID","655","INTEG MKTG & OPERATIONS"],
  ["OID","656","OPERATIONS STRATEGY"],
  ["OID","658","SERVICE OPER MGMT"],
  ["OID","659","ADVANCED TOPICS"],
  ["OID","662","ENABLING TECHNOLOGIES"],
  ["OID","664","DATABASE&INFO MGMT SYS"],
  ["OID","665","OM IN HEALTH CARE"],
  ["OID","669","ADV TOPICS IN INFO STRAT"],
  ["OID","670","SPECIAL TOP IN INFO SYS"],
  ["OID","672","DATA MINING BUS INTEL"],
  ["OID","673","GLOBAL SUPPLY CHAIN MGMT"],
  ["OID","676","ELECTRONIC MARKETS"],
  ["OID","690","MANAG DECSN MAKING"],
  ["OID","691","NEGOTIATIONS"],
  ["OID","693","INFLUENCE"],
  ["OID","697","RETAIL SUPP CHAIN MGMT"],
  ["OID","698","RETAIL SUPPLY CHAINS"],
  ["OID","761","RISK ANALY & ENV MGMT"],
  ["OID","762","ENVRNMTL SUS&VAL CRTN"],
  ["OID","763","ENERGY MARKETS & POLICY"],
  ["OID","898","ADVANCED TOPICS"]
]

puts "Creating Departments..."

department_list.each do |department_code, department_description|
  Department.create(department_code: department_code, department_description: department_description)
end

puts "Creating Lecturers..."

lecturers_list.each do |department_code, firstname, lastname|
  department = Department.find_by(department_code: department_code)
  Lecturer.create(department: department, firstname: firstname, lastname: lastname)
end

puts "Creating Courses..."

courses_list.each do |department_code, course_code, course_description|
  department = Department.find_by(department_code: department_code)
  Course.create(department: department, course_code: course_code, course_description: course_description)
end

puts "Creating File Types"

file_type_list.each do |file_type_name|
  FileType.create(file_type: file_type_name)
end
